config/routes.rb
Onzeer::Application.routes.draw do

  resource :session do
    member do 
      get :openid_complete
    end
  end

  resources :tokens

  resources :users do
    resources :lists
  end

  resources :tracks do
    member do
      post :just_listened
    end
    collection { post :wanted}
  end

  resources :albums do
    member do
      post :like
      post :hate
      delete :destroy_vote
      get :mb_releases
    end
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  # match 'blog' :to => "posts"

  resources :lists do
    member do
      post :follow
      post :add_album
      delete :remove_album
      post :accept_modification
      delete :reject_modification
    end
  end

  root :to => 'home#index'

end

app/models/list.rb
class List
  # include MongoMapper::Document
  # 
  # key :name, String, :required => true
  # many :modifications
  # key :author_id, String, :required => true
  # # belongs_to :author, :class_name => "User"
  # 
  # include Timestamp
  # timestamps

  # after_save :create_author_user_list

  def author=(author)
    self.author_id = author.id
  end

  def author
    @author ||= author_id && User.find(author_id)
  end

  def add(params)
    add_or_remove(:add, params)
  end

  def remove(params)
    add_or_remove(:remove, params)
  end

  def follow_by(user)
    user_list = user.list_by_id(id)
    return user_list if user_list
    user_list = UserList.new(:name => name, :list_id => id)
    user.user_lists << user_list
    user.save
    modifications.each do |modification|
      modification.list = self
      modification.accept(:author => user)
    end
    user_list
  end

  def add_or_remove(action, params)
    author_id = params[:author_id]
    author_id ||= params[:author] && params[:author].id
    album_id = params[:album_id]
    raise "missing :author_id or author" unless author_id
    raise "missing :album_id" unless author_id
    author = params[:author] || User.find(author_id)
    user_list = follow_by(author)
    modification = Modification.new(:author_id => author_id, :action => action.to_s, :album_id => album_id)
    modification.list = self
    modifications << modification
    save
    modification.accept(:author => author)
  end

protected
  def create_author_user_list
    user_list = author.list_by_id(id)
    unless user_list
      user_list = UserList.new(:name => name, :list_id => id)
      author.user_lists << user_list
      author.save
    end
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    user = params[:user_id] ? User.find(params[:user_id]) : current_user
    @lists = user.user_lists.each{|l| l.user = user}
    @new_list = List.new
  end

  def create
    list = List.new(params[:list])
    list.author = current_user
    list.save
    redirect_to :action => :index
  end

  def add_album
    list.add(:album_id => params[:album_id], :author => current_user)
    list_in_album_update_response
  end

  def remove_album
    list.remove(:album_id => params[:album_id], :author => current_user)
    list_in_album_update_response
  end

  def accept_modification
    logger
    modification && modification.accept(:author => current_user)
    redirect_to :action => :index
  end

  def reject_modification
    modification && modification.reject(:author => current_user)
    redirect_to :action => :index
  end

  def follow
    list.follow_by(current_user)
    redirect_to :action => :index
  end

protected

  def list_in_album_update_response
    respond_to do |format|
      format.js do
        @album = Album.find(params[:album_id])
        render :partial => "albums/lists"
      end
      format.html do
        redirect_to album_path(params[:album_id])
      end
    end
  end

  def list
    @list ||= List.find(params[:id])
  end

  def modification
    @modification ||= list.modifications.detect{|m| m.id.to_s == params[:modification_id]}
    @modification.list = list
    @modification
  end

end

app/views/lists/index.html.haml
.mine
  %h2 mes listes d'albums

  %ul
    - @lists.each do |list|
      %li
        %h3=h list.name
        %span.count= "(#{pluralize(list.album_ids.length, "album")})"
        - if list.list.author.id != list.user.id
          %span.participation= "Participation à la liste de #{list.list.author.nickname}"
        - unless list.album_ids.blank?
          - paginator = Paginator.new(list.album_ids, :class => Album)
          .albums_group= render :partial => "albums/paginated", :locals => {:albums => paginator.objects_in_page, :paginator => paginator, :albums_params => {:user_id => list.user.id, :list_id => list.list_id}}

        - unless list.pending_modifications.blank?
          %ul.pending_modifications
            - list.pending_modifications.each do |modification|
              %li
                %span.author= modification.author.nickname
                %span.action= modification.action == "add" ? "propose d'ajouter" : "propose d'enlever"
                %span.album= "l'album : " + album_name_with_link(modification.album)
                .accept
                  - form_tag accept_modification_list_path(modification.list) do
                    = hidden_field_tag "modification_id", modification.id
                    = submit_tag "accepter"
                .reject
                  - form_tag reject_modification_list_path(modification.list), :method => :delete do
                    = hidden_field_tag "modification_id", modification.id
                    = submit_tag "rejeter"


  .new
    %h3 Ajouter une nouvelle liste
    - form_for @new_list, :url => lists_path, :html => {:method => :POST} do |f|
      .title
        = f.text_field :name

      = submit_tag "Ajouter"


.others
  %h2 Listes d'autres utilisateurs
  %ul
    - List.all.delete_if{|list| @lists.map(&:list_id).include?(list.id)}.each do |list|
      %li
        %span.name= list.name
        %span.author= list.author.nickname
        .follow
          - form_tag follow_list_path(list) do
            = submit_tag "participer"