config/routes.rb
Onzeer::Application.routes.draw do

  resource :session do
    member do 
      get :openid_complete
    end
  end

  resources :tokens

  resources :users do
    resources :lists
  end

  resources :tracks do
    member do
      post :just_listened
    end
    collection { post :wanted}
  end

  resources :albums do
    member do
      post :like
      post :hate
      delete :destroy_vote
      get :mb_releases
    end
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  # match 'blog' :to => "posts"

  resources :lists do
    member do
      post :follow
      post :add_album
      delete :remove_album
      post :accept_modification
      delete :reject_modification
    end
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :ensure_activated

  def index
    @last_blog_post = Post.last
    @last_listenings = TrackListening.find().sort(['_id', 'descending']).limit(10)
    @last_comments = UserComment.find().sort(['_id', 'descending']).limit(10)
    @last_albums = Album.find_last
    @users = User.all.sort_by{|u| u.last_uploaded_albums.empty? ? 0 : u.last_uploaded_albums.total_entries}.reverse
  end

end

app/views/home/index.html.haml
.search
  Chercher un album
  - form_tag albums_path, :method => :get do
    = text_field_tag :q
    = submit_tag "Rechercher"


%p= link_to "liste (très moche) des albums", albums_path
%p= link_to "ajouter des fichiers", new_track_path

%ul.two_cols
  %li.left_col
    .randomly
      %h3 Albums choisis aléatoirement:
      .albums_group=render :partial => "albums/randomly"
    .last_albums
      %h3 les derniers albums importés:
      .albums_group=render :partial => "albums/paginated", :locals => {:albums => @last_albums, :albums_params => {:last => true}}

    .users
      %h2 Utilisateurs
      %ul
        - @users.each do |user|
          - votes = user.last_votes
          - last_uploaded = user.last_uploaded_albums
          - unless votes.empty? && last_uploaded.empty?
            %li
              %h3.nickname=h(user.nickname)
              - unless votes.empty?
                %p= "#{votes.total_entries} albums préférés."
                .albums_group
                  = render :partial => "albums/paginated", :locals => {:albums => votes.map(&:album), :paginator => votes, :albums_params => {:user_id => user.id, :preferred => true}}
              - unless last_uploaded.empty?
                %p= "#{last_uploaded.total_entries} albums uploadés."
                .albums_group
                  = render :partial => "albums/paginated", :locals => {:albums => last_uploaded, :albums_params => {:user_id => user.id, :last => true}}

  %li.right_col
    - if @last_blog_post
      .last_blog_post
        %h3 Sur le blog :
        = link_to @last_blog_post.title, posts_path

    .last_comments.last_thing
      %h3 derniers commentaires :
      %ul
        - @last_comments.each do |user_comment|
          %li
            .main_info
              %p.cover
                = cover_img_tag(user_comment.album, 20)
              %p.author
                =h user_comment.author.nickname
            .more_info
              %p.album_name
                =h user_comment.album && link_to(user_comment.album.name, album_path(user_comment.album))
              %p.comment
                =h user_comment.comment.body

    .last_listenings.last_thing
      %h3 dernières écoutes :
      %ul
        - @last_listenings.each do |track_listening|
          %li
            .main_info
              %p.cover
                = cover_img_tag(track_listening.album, 20)
              %p.author
                = track_listening.user && track_listening.user.nickname
            .more_info
              %p.album_name
                = track_listening.album && link_to(track_listening.album.name, album_path(track_listening.album))
              %p.title
                = track_listening.track && track_listening.track.title

  %li.clear