config/routes.rb
Onzeer::Application.routes.draw do

  resource :session do
    member do 
      get :openid_complete
    end
  end

  resources :tokens

  resources :users do
    resources :lists
  end

  resources :tracks do
    member do
      post :just_listened
    end
    collection { post :wanted}
  end

  resources :albums do
    member do
      post :like
      post :hate
      delete :destroy_vote
      get :mb_releases
    end
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  # match 'blog' :to => "posts"

  resources :lists do
    member do
      post :follow
      post :add_album
      delete :remove_album
      post :accept_modification
      delete :reject_modification
    end
  end

  root :to => 'home#index'

end

app/models/album.rb
class Album

  include MongoRecord
  include Timestamp

  key :artist #, String, :required => true
  key :name #, String, :required => true
  key :track_ids #, Array, :required => true
  key :cover #, String
  key :amazon_asin #, String
  key :musicbrainz_release_id #, String

  key :user_id #, String # author

  many :votes
  many :comments

  def self.find_randomly(number = 10)
    count = self.count
    (0...number).map{ find().limit(1).skip(rand(count)).first()}.compact
  end

  def self.find_last(page=nil)
    Album.paginate(:order => ['_id', 'descending'], :per_page => 10, :page => page)
  end

  def self.find_or_create_by_artist_and_name(artist,name)
    album = find(:artist => artist, :name => name).first
    return album if album
    album = new(:artist => artist, :name => name)
    album.save
    album
  end

  def before_save
    set_timestamps(comments)
  end

  def after_save
    update_tracks
  end

  def track_ids
    self.attributes['track_ids'] ||= []
  end

  def tracks
    return @tracks if @tracks
    @tracks = Track.find(:_id => {'$in' => track_ids}).sort('nb')
  end

  def artist=(value)
    @need_tracks_update = true
    self.attributes['artist'] = value
  end

  def name=(value)
    @need_tracks_update = true
    self.attributes['name'] = value
  end

  def save_user_comment_for(comment)
    UserComment.create(:album_id => id, :comment_id => comment.id, :author_id => comment.author_id)
  end

  def update_tracks
    return unless @need_tracks_update
    tracks.each do |track|
      track.update_attributes(:artist => artist, :album_name => name) unless track.album_name == name && track.artist == artist
    end
  end
  protected :update_tracks

  def find_cover
    track = tracks.detect{|t| t.cover}
    self.cover = track && track.cover
  end

  def public_cover_path
    cover && Track.public_cover_path(cover)
  end

  def add_track(track)
    track_ids << track.id unless track_ids.include?(track.id)
    self.cover ||= track.cover
  end

  def remove_track(track)
    track_ids.delete(track.id) if track_ids.include?(track.id)
  end

  def loved_by(user)
    UserVote.delete_all(:album_id => id, :author_id => user.id)
    votes.delete_if{|v| v.author_id == user.id}
    votes << Vote.new(:note => 1, :author_id => user.id)
    UserVote.create(:album_id => id, :author_id => user.id, :note => 1)
  end

  def lovers
    @lovers ||= votes.select{|v| v.note > 0}.map(&:author)
  end

  def hated_by(user)
    UserVote.delete_all(:album_id => id, :author_id => user.id)
    votes.delete_if{|v| v.author_id == user.id}
    votes << Vote.new(:note => -1, :author_id => user.id)
    # only create UserVote for positive ones for now.
    # UserVote.create(:album_id => id, :author_id => user.id, :note => -1)
  end

  def haters
    @haters ||= votes.select{|v| v.note < 0}.map(&:author)
  end

  def remove_vote_of(user)
    UserVote.delete_all(:album_id => id, :author_id => user.id)
    votes.delete_if{|v| v.author_id == user.id}
  end

  def musicbrainz_query
    {
      :query=>"#{name} AND artist:\"#{artist}\"",
      :type=> "release",
      :adv=> "on",
      :handlearguments => 1
    }
  end
# http://musicbrainz.org/doc/MusicBrainzIdentifier
# http://musicbrainz.org/doc/Disc_ID_Calculation
  def discid
    # CDDB1 identifies CDs with a 32-bit number, usually displayed as a hexadecimal number containing 8 digits: XXYYYYZZ.
    # The first two digits (labeled XX) represent a checksum based on the starting times of each track on the CD, mod 255.
    # The next four digits (YYYY) represent the total time of the CD in seconds from the start of the first track to the end of the last track.
    # The last two digits (ZZ) represent the number of tracks on the CD.
    return @discid if @discid
    checksum = 0
    checksum = checksum.modulo(255)
    total_time = tracks.map(&:seconds).sum
    nb = tracks.length
    @discid = "%02x%04x%02x" % [checksum, total_time, nb]
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    conditions = {}
    if q = params[:q]
     conditions = { '$or' => [ {"name" => /#{q}/i}, {'artist' => /#{q}/i} ] }
    end
    if params[:randomly]
      @albums = Album.find_randomly
      render :partial => "albums/randomly"
      return
    end
    if params[:last]
      albums_params = {:last => true}
      if params[:user_id]
        user = User.find(params[:user_id])
        albums_params[:user_id] = user.id
        albums = user.last_uploaded_albums(params[:page])
      else
        albums = Album.find_last(params[:page])
      end
      render :partial => "albums/paginated", :locals => {:albums => albums, :albums_params => albums_params}
      return
    end
    if params[:user_id] && params[:preferred]
      user = User.find(params[:user_id])
      votes = user.last_votes(params[:page])
      render :partial => "albums/paginated", :locals => {
        :albums => votes.map(&:album),
        :paginator => votes,
        :albums_params => {:user_id => user.id, :preferred => true}
      }
      return
    end
    if params[:user_id] && params[:list_id]
      user = User.find(params[:user_id])
      list = user.list_by_id(params[:list_id])
      paginator = Paginator.new(list.album_ids, :class => Album, :page => params[:page])
      render :partial => "albums/paginated", :locals => {
        :albums => paginator.objects_in_page,
        :paginator => paginator,
        :albums_params => {:user_id => list.user.id, :list_id => list.list_id}
      }
      return
    end

    @albums ||= Album.paginate(:order => 'artist, name', :per_page => params[:limit] || 50, :conditions => conditions, :page => params[:page])
  end

  def show
    album
    respond_to do |format|
      format.html {}
      format.json do
        render :json => MongoEmbeddedRecord.json_encoder({ :view => render_to_string(:action => "show.html", :layout => false), :tracks => album.tracks.map{|r| r.attributes} }).to_json
      end
    end
  end

  def edit
    album
  end

  def update
    if album.update_attributes(params[:album])
      redirect_to album
    else
      render :action => :edit
    end
  end

  def mb_releases
    @releases = MusicBrainzRelease.find_all_by_title_and_artist(album.name, album.artist)
  end

  def like
    album.loved_by(current_user)
    album.save
    like_or_hate_response
  end

  def hate
    album.hated_by(current_user)
    album.save
    like_or_hate_response
  end

  def destroy_vote
    album.remove_vote_of(current_user)
    album.save
    like_or_hate_response
  end

  protected
  def like_or_hate_response
    respond_to do |format|
      format.html { redirect_to album }
      format.js { render :partial => "votes"}
    end
  end

  def album
    @album ||= Album.find(params[:id])
  end

end

app/views/albums/_comments.html.haml
.comments
  %h3= pluralize(@album.comments.length, "commentaire")
  %ul.comments
    - @album.comments.each do |comment|
      %li
        %p.body
          =h(comment.body).gsub("\n","<br />\n")
        %p.author
          =h(comment.author.nickname)
        / %p.date
        /   =h(comment.created_at)
        - if comment.author == current_user
          %p.edit
            = link_to "edit", edit_album_comment_path(@album, comment)
    %li.new
      = link_to "add a comment", new_album_comment_path(@album)

app/views/albums/_lists.html.haml
.lists
  - in_lists = current_user.user_lists.select{|list| list.album_ids.include?(@album.id)}
  - other_lists = current_user.user_lists - in_lists
  .in_lists
    - unless in_lists.blank?
      %p Dans les listes suivantes :
      %ul
        - in_lists.each do |list|
          %li
            %span.name=h list.name
            .remove
              - form_tag remove_album_list_path(list.list_id), :method => :delete do
                = hidden_field_tag :album_id, @album.id
                = submit_tag "enlever"

  .not_in_lists
    - unless other_lists.blank?
      %p l'ajouter à une liste :
      %ul
        - other_lists.each do |list|
          %li
            %span.name=h list.name
            .add
              - form_tag add_album_list_path(list.list_id) do
                = hidden_field_tag :album_id, @album.id
                = submit_tag "ajouter"

app/views/albums/_paginated.html.haml
- paginator ||= albums
%ul.links
  %li{:class => "#{"empty" unless paginator.previous_page}"}
    - if paginator.previous_page
      = link_to "«", albums_path(albums_params.merge(:page => paginator.previous_page))
  %li{:class => "#{"empty" unless paginator.next_page}"}
    - if paginator.next_page
      = link_to "»", albums_path(albums_params.merge(:page => paginator.next_page))

%ul.albums
  - albums.each do |album|
    %li= album_div(album)

app/views/albums/_randomly.html.haml
%ul.links
  %li.last= link_to "∞", albums_path(:randomly => true)
%ul.albums
  - Album.find_randomly.each do |album|
    %li= album_div(album)

app/views/albums/_votes.html.haml
.votes
  - title_parts = []
  - title_parts << pluralize(@album.lovers.length, 'personne')+ " pour" if @album.lovers.length > 0
  - title_parts << pluralize(@album.haters.length, 'personne')+ " contre" if @album.haters.length > 0
  - title = title_parts.empty? ? "aucun vote." : title_parts.join(', ')+'.'
  %h3{:title => title}
    = pluralize(@album.lovers.length + @album.haters.length, 'vote')
  %ul
    - in_it = @album.lovers.include?(current_user)
    %li.lovers{:class => in_it && "me", :title => in_it ? "me retirer des pour" : "m'ajouter aux pour"}
      %h4= pluralize(@album.lovers.length, "fan")
      %ul
        - @album.lovers.each do |account|
          %li
            =h(account.nickname)
        - if in_it
          %li.remove_me
            - form_for :vote, :url => destroy_vote_album_path(@album), :html => {:method => :delete} do |f|
              = f.submit "remove my vote"
        - else
          %li.me
            - form_for :vote, :url => like_album_path(@album) do |f|
              = f.submit "I like it !"
    - in_it = @album.haters.include?(current_user)
    %li.haters{:class => in_it && "me", :title => in_it ? "me retirer des contre" : "m'ajouter aux contre"}
      %h4= pluralize(@album.haters.length, "anti")
      %ul
        - @album.haters.each do |account|
          %li
            = h(account.nickname)
        - if in_it
          %li.remove_me
            - form_for :vote, :url => destroy_vote_album_path(@album), :html => {:method => :delete} do |f|
              = f.submit "remove my vote"
        - else
          %li.me
            - form_for :vote, :url => hate_album_path(@album) do |f|
              = f.submit "I hate it !"

app/views/albums/edit.html.haml
- form_for(@album) do |f|
  - [:artist, :name, :amazon_asin, :musicbrainz_release_id].each do |attribute_name|
    %p{:class => attribute_name}
      = f.label attribute_name
      = f.text_field attribute_name

  = f.submit "Save"

= link_to "MusicBrainz search", "http://musicbrainz.org/search/textsearch.html?#{@album.musicbrainz_query.to_param}"

app/views/albums/index.html.haml
- if @albums.total_pages > 1
  %p.pagination
    - (1..@albums.total_pages).each do |page|
      - if page == @albums.current_page
        %span.current
          = page
      - else
        = link_to page, albums_path(params.merge(:page => page))

%ul.albums
  - @albums.each do |album|
    %li
      .cover
        = cover_img_tag(album)
      %span.artist
        =h album.artist
      %span.name
        =link_to  h(album.name), album_path(album)
      / %ul.tracks
      /   = render :partial => "tracks/track", :collection => album.tracks

- if @albums.total_pages > 1
  %p.pagination
    - (1..@albums.total_pages).each do |page|
      - if page == @albums.current_page
        %span.current
          = page
      - else
        = link_to page, albums_path(:page => page)

app/views/albums/mb_releases.html.haml
- @releases.each do |release|
  .release
    %p.artist= release["artist"]["name"]
    %p.title= release["title"]
    %p.tracks_count= pluralize(release["track_list"]["count"], "track")
    - if release["asin"]
      %p.amazon_cover= cover_from_amazon_asin(release["asin"])

    - form_for(@album) do |f|
      - @album.amazon_asin = release["asin"]
      - @album.musicbrainz_release_id = release["id"]
      = f.hidden_field :amazon_asin
      = f.hidden_field :musicbrainz_release_id
      = submit_tag "save"

= "No results found" if @releases.empty?

app/views/albums/show.html.haml
#player

.album
  %span.artist
    =h @album.artist
  %span.album_name
    =h @album.name

  .tracks.playable
    %h3= pluralize(@album.tracks.count, "morceau", "morceaux")
    %ul
      = render :partial => "tracks/track.html", :collection => @album.tracks.map{|r| r}

  = javascript_tag "tracks = #{MongoEmbeddedRecord.json_encoder(@album.tracks.map(&:attributes)).to_json};"

  - if current_user.admin?
    %p.edit
      = link_to :edit, edit_album_path(@album)

  %ul.links
    - if !@album.musicbrainz_release_id.blank?
      %li.musicbrainz
        = link_to "MusicBrainz.org", "http://musicbrainz.org/release/#{@album.musicbrainz_release_id}.html"
    - elsif current_user.admin?
      %li.musicbrainz.find
        = link_to "Find MusicBrainz Releases", mb_releases_album_path(@album)

    - if !@album.amazon_asin.blank?
      %li.amazon{:class => "asin_#{@album.amazon_asin}"}
        = link_to "Amazon", "http://www.amazon.fr/gp/product/#{@album.amazon_asin}"

  = render :partial => "votes.html"

  = render :partial => "comments.html"

  = render :partial => "lists.html"