config/routes.rb
Onzeer::Application.routes.draw do

  resource :session do
    member do 
      get :openid_complete
    end
  end

  resources :tokens

  resources :users do
    resources :lists
  end

  resources :tracks do
    member do
      post :just_listened
    end
    collection { post :wanted}
  end

  resources :albums do
    member do
      post :like
      post :hate
      delete :destroy_vote
      get :mb_releases
    end
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  # match 'blog' :to => "posts"

  resources :lists do
    member do
      post :follow
      post :add_album
      delete :remove_album
      post :accept_modification
      delete :reject_modification
    end
  end

  root :to => 'home#index'

end

app/models/post.rb
class Post

  include MongoRecord
  include Timestamp

  key :title #, String, :required => true
  key :body # String, :required => true
  key :author_id #, String, :required => true

  many :comments

  def before_save
    set_timestamps(comments)
  end

  def author
    @author ||= User.find(author_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.sort(['_id','desc'])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    @post.author_id = current_user.id
    if @post.save
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :action => :new
  end

  def update
    @post = Post.find(params[:id])
    @post.author_id = current_user.id
    if @post.update_attributes(params[:post])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

end

app/views/posts/index.html.haml
%ul.posts
  - @posts.each do |post|
    %li.post
      %h1= post.title
      - if current_user.admin?
        .action= link_to "edit", edit_post_path(post)
      .body= post.body
      .author= post.author && post.author.nickname
      .timestamp= post.created_at && post.created_at.to_s(:db)
      
      .comments
        %p.summary= no_one_or_n_comments(post.comments)
        %ul.comments
          - post.comments.each do |comment|
            %li
              .body= comment.body
              .author_and_date
                %span.author= comment.author.nickname
                ,
                %span.date= comment.created_at.to_s(:db) if comment.created_at
                
          %li.new_comment
            = form_for(@comment, :url => post_comments_path(post), :html => {:method => :post}) do |f|
              = f.text_area :body
              = f.submit "Send"

app/views/posts/new.html.haml
- form_for @post do |f|
  .title
    = f.label :title, "Titre :"
    = f.text_field :title

  .body
    %div= f.text_area :body

  = submit_tag "Sauver"
 